import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

import { globalStyles } from './globalStyles';

export const createAccountStyles = StyleSheet.create({
  content: {
    backgroundColor: globalStyles?.colorSecondary.color,
  },
  header: {
    width: '100%',
    paddingTop: 50,
    paddingBottom: 30,
    height: 150,
    backgroundColor: globalStyles?.colorSecondary.color,
    color: globalStyles?.colorWhite.color,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'WalsheimProRegular',
  },
  signUpContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingTop: 30,
    paddingHorizontal: 20,
    height: Dimensions.get('window').height - 100,
  },
  input: {
    fontFamily: 'WalsheimProLight',
    fontSize: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    marginBottom: -16,
    borderColor: '#ddd',
    color: '#222',
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
  },
  errorText: {
    fontSize: 12,
    fontWeight: 'normal',
    padding: 0,
    margin: 5,
    textAlign: 'left',
  },

  buttonFacebook: {
    position: 'relative',
    backgroundColor: '#1877F2',
    borderRadius: 12,
    paddingTop: 18,
    paddingBottom: 20,
    paddingHorizontal: 22,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  buttonTwitter: {
    backgroundColor: '#1DA1F2',
    borderRadius: 12,
    paddingTop: 18,
    paddingBottom: 20,
    paddingHorizontal: 22,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  buttonGoogle: {
    backgroundColor: '#EFF3F5',
    borderRadius: 12,
    paddingTop: 18,
    paddingBottom: 20,
    paddingHorizontal: 22,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  buttonImageFacebook: {
    position: 'absolute',
    top: 12.5,
    left: 8,
    height: 25,
    resizeMode: 'contain',
  },
  buttonImageTwitter: {
    position: 'absolute',
    top: 20,
    left: 2,
    height: 18,
    resizeMode: 'contain',
  },
  buttonImageGoogle: {
    position: 'absolute',
    top: 16,
    left: -4,
    height: 24,
    resizeMode: 'contain',
  },
  buttonTextPrimary: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'WalsheimProBold',
  },
  buttonSocialTextLight: {
    fontFamily: 'WalsheimProLight',
    color: '#FFFFFF',
  },
  buttonSocialTextDark: {
    fontFamily: 'WalsheimProLight',
    color: '#0C010C',
  },
  orContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 12,
    marginBottom: 12,
  },
  horizontalLine: {
    borderBottomColor: '#707070',
    borderBottomWidth: 1,
    width: '44%',
    opacity: 0.15,
    marginTop: 2,
  },
  horizontalLineText: {
    fontFamily: 'WalsheimProLight',
    width: '10%',
    color: 'black',
    opacity: 0.35,
    textAlign: 'center',
    fontSize: 16,
  },
});
